name: "Reusable Docker Build"

on:
  workflow_call:
    inputs:
      subdir:
        required: true
        type: string
env:
  PACKAGE: "ghcr.io/drewpackages/engine/workers/${{ inputs.subdir }}"
  IMAGEDIR: jobs/${{ inputs.subdir }}

permissions:
  packages: write

jobs:
  buildAndPublish:
    name: "Build and publish"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.IMAGEDIR }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.IMAGEDIR }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.PACKAGE }}:latest
