name: Docker Compose worker image

on:
  push:
    branches:
      - "main"
    paths:
      - "jobs/docker-compose/**"
      - ".github/workflows/worker-docker-compose.yml"
      - ".github/workflows/docker.yml"

jobs:
  imageBuild:
    permissions:
      packages: write
    uses: "./.github/workflows/docker.yml"
    with:
      subdir: "docker-compose"
    secrets: inherit
