name: Blueprint worker image

on:
  push:
    branches:
      - "main"
    paths:
      - "jobs/blueprint/**"
      - ".github/workflows/worker-blueprint.yml"
      - ".github/workflows/docker.yml"

jobs:
  imageBuild:
    permissions:
      packages: write
    uses: "./.github/workflows/docker.yml"
    with:
      subdir: "blueprint"
    secrets: inherit
